[cpphs @ 2004-10-06 15:30:18 by malcolm]
Allow for testing different builds of cpphs.

diff --git a/tests/runtests b/tests/runtests
--- a/tests/runtests
+++ b/tests/runtests
@@ -1,32 +1,36 @@
 #!/bin/sh
+CPPHS=${1:-"../cpphs"}
+FAIL=0
 
 runtest() {
   if $1 >out && diff -q $2 out >/dev/null
   then echo "passed: " $1
-  else echo "FAILED: ($2) " $1
+  else FAIL=$?
+       echo "FAILED: ($2) " $1
   fi
 }
 
-runtest "../cpphs --nomacro testfile" expect1
-runtest "../cpphs --nomacro -Dnoelif testfile" expect2
-runtest "../cpphs --nomacro -Delif testfile" expect3
-runtest "../cpphs --nomacro -Dinclude testfile" expect4
-runtest "../cpphs --noline -Dinclude testfile" expect5
-runtest "../cpphs cpp" expect6
-runtest "../cpphs -D__GLASGOW_HASKELL__ --layout Storable.hs " expect7
-runtest "../cpphs -DCALLCONV=ccall --hashes --layout HsOpenGLExt.h" expect8
-runtest "../cpphs --layout multiline" expect9
-runtest "../cpphs --nomacro multiline" expect10
-runtest "../cpphs --hashes stringise" expect11
-runtest "../cpphs recursive" expect12
-runtest "../cpphs --strip ross" expect13
-runtest "../cpphs precedence" expect14
-runtest "../cpphs indirect" expect15
-runtest "../cpphs numbers" expect16
-runtest "../cpphs pragma" expect17
-runtest "../cpphs --noline pragma" expect18
-runtest "../cpphs -D__NHC__=117 parens" expect19
-runtest "../cpphs -Dc -Dd -De -Df -Dg -Dh chains" expect20
-runtest "../cpphs --hashes specials" expect21
-runtest "../cpphs --hashes specialinclude" expect22
-runtest "../cpphs incomplete" expect23
+runtest "$CPPHS --nomacro testfile" expect1
+runtest "$CPPHS --nomacro -Dnoelif testfile" expect2
+runtest "$CPPHS --nomacro -Delif testfile" expect3
+runtest "$CPPHS --nomacro -Dinclude testfile" expect4
+runtest "$CPPHS --noline -Dinclude testfile" expect5
+runtest "$CPPHS cpp" expect6
+runtest "$CPPHS -D__GLASGOW_HASKELL__ --layout Storable.hs " expect7
+runtest "$CPPHS -DCALLCONV=ccall --hashes --layout HsOpenGLExt.h" expect8
+runtest "$CPPHS --layout multiline" expect9
+runtest "$CPPHS --nomacro multiline" expect10
+runtest "$CPPHS --hashes stringise" expect11
+runtest "$CPPHS recursive" expect12
+runtest "$CPPHS --strip ross" expect13
+runtest "$CPPHS precedence" expect14
+runtest "$CPPHS indirect" expect15
+runtest "$CPPHS numbers" expect16
+runtest "$CPPHS pragma" expect17
+runtest "$CPPHS --noline pragma" expect18
+runtest "$CPPHS -D__NHC__=117 parens" expect19
+runtest "$CPPHS -Dc -Dd -De -Df -Dg -Dh chains" expect20
+runtest "$CPPHS --hashes specials" expect21
+runtest "$CPPHS --hashes specialinclude" expect22
+runtest "$CPPHS incomplete" expect23
+exit $FAIL
